### ISSUE TITLE
Fails in a Server Environment

### ISSUE THREAD

**Issue by BlazingTwist** [tyap-lyap/hidden-realm#1]
Used version: `0.1.3+1.21`
On a dedicated server for mc `1.21.1`

Results in
```
[03:34:52] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hiddenrealm' at 'ru.pinkgoosik.hiddenrealm.HiddenRealmMod'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.particle.v1.ParticleFactoryRegistry$PendingParticleFactory in environment type SERVER
        at ru.pinkgoosik.hiddenrealm.registry.HiddenRealmParticles.<clinit>(HiddenRealmParticles.java:13) ~[hidden-realm-0.1.3+1.21.jar:?]
        at ru.pinkgoosik.hiddenrealm.HiddenRealmMod.onInitialize(HiddenRealmMod.java:31) ~[hidden-realm-0.1.3+1.21.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.particle.v1.ParticleFactoryRegistry$PendingParticleFactory in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at ru.pinkgoosik.hiddenrealm.registry.HiddenRealmParticles.<clinit>(HiddenRealmParticles.java:13) ~[hidden-realm-0.1.3+1.21.jar:?]
        at ru.pinkgoosik.hiddenrealm.HiddenRealmMod.onInitialize(HiddenRealmMod.java:31) ~[hidden-realm-0.1.3+1.21.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more
```

**Comment by PinkGoosik** [comment]
Thanks for the report, fixed in 0.1.4+1.21
